### ISSUE TITLE
Writing GeoStack to NetCDF broken in version 0.5

### ISSUE THREAD

**Issue by bgroenks96** [rafaqz/Rasters.jl#202]
The latest release (version 0.5) breaks writing `GeoStack`s to `NetCDF` via `NCDatasets`.

The following works fine on 0.4.6 but now fails:

```julia
using GeoData, NCDatasets
data = stack("dataset.nc")
write("/tmp/dataset.nc", NCDstack, data)
```

```
ERROR: MethodError: no method matching write(::IOStream, ::typeof(NCDstack))
```

**Comment by bgroenks96** [comment]
Also worth noting that `GeoData` or `NCDatasets` is inferring the type wrong on the NetCDF data. It gets read as `Int16` even though the values are floats. I guess this should be a separate issue.

This release seems to have broken a lot of stuff!

**Comment by rafaqz** [comment]
This is just syntax change - its a minor release and there are quite a few because most of the internals are different now.

There is no `NCDstack` type at all - its all `GeoStack` NCDstack only exists so the `NCDstack(filename)` command still works for a while. 

Just don't include the `NCDstack` in the command, like:

```julia
using GeoData, NCDatasets
data = GeoStack("dataset.nc")
write("/tmp/dataset.nc", data)
```

It's all detected automatically now. `stack` is now depreciated as well to simplify - as the `GeoStack` constructor is identical to `stack` now.

**Comment by rafaqz** [comment]
I should probably rewrite the docs to `write` a bit, there are some things I've missed there and the order is confusing.

How would you normally try to find out about syntax changes? Depreciations dont show in the REPL anyway now so they're not that useful for this kind of thing.

**Comment by rafaqz** [comment]
It no longer prints one unless you use a flag for that. Otherwise `stack` would warn above...

But yes, I should start writing a change log and updating the release notes. The reality is I've been sick for three weeks and have a course coming up teaching with GeoData.jl, so some corners have been cut. I also maintain too many packages.

You can also read the docs for `write` and see that your syntax no longer exists, as well ;)
