### ISSUE TITLE
Should summary functions ignore NoData by default?

### ISSUE THREAD

**Issue by vlandau** [rafaqz/Rasters.jl#229]
When using functions like `minimum`, `maximum`, etc, on a Raster, the missingval is included. Should it be excluded by default? Or maybe new methods for each can be added with a kwarg like `ignoremissingval` so the user can decide?

Right now, I'm doing this to ignore the missingval:

```julia
minimum(raster[raster .!= raster.missingval])
```

That workaround can suffice for now, but I thought the topic was worth bringing up. This is something I can possibly handle a PR for if it is desirable.

**Comment by rafaqz** [comment]
Its something I've been thinking about too. You can use `replace_missing` to swap `missingval` to `missing` and then use `skipmissings`... but it's not a great workflow.

One option that might help is to use [SentinelMissings.jl](https://github.com/meggart/SentinelMissings.jl) internally in Rasters.jl and always present the `missingval` as `missing`. So this would just work how you want:

```julia
minimum(skipmissing(raster))
```

What do you think?

**Comment by maxfreu** [comment]
Regarding the original question: I don't think missing values should be filtered by default.

How to do it is another question. I think it's best to use [Transducers.jl](https://juliafolds.github.io/Transducers.jl/stable/tutorials/tutorial_missings/).

```julia
using Rasters
using Transducers
using SentinelMissings
using BenchmarkTools

N=4096
data = rand(Int32, N, N);
dims = X(1:N), Y(1:N)
r = Raster(data, dims; missingval=-9999);
r[N÷2:end, N÷2:end] .= -9999

rs = as_sentinel(r, r.missingval)

# non-allocating, handwritten code for reference
function minimum_skipmissingval(x::AbstractArray{T}, missingval) where T
    min_ = typemax(T)
    for v in x
        v == missingval && continue
        if v < min_
            min_ = v
        end
    end
    return min_
end

@btime minimum_skipmissingval($r, $r.missingval)         # 14ms, 0 allocs
@btime minimum($r[$r .!= $r.missingval])                 # 96ms, 6 allocs 49MB
@btime minimum(filter(x -> x != $r.missingval, $r))      # 95ms, 5 allocs 175MB
@btime minimum(skipmissing(replace_missing($r)))         # 61ms, 8 allocs 80MB
@btime minimum(skipmissing($rs))                         # 82ms, 0 allocs
@btime minimum(replace_missing($r, Inf32))               # 48ms, 2 allocs 64MB
@btime $r |> Filter(x -> x != $r.missingval) |> minimum  # 14ms, 0 allocs
@btime $rs |> Filter(ismissing) |> minimum               # 16ms, 2 allocs 112kB
```

The second option is slowest because it allocates a temporary array. Transducers are basically as fast as the hand-written code, but can be parallelized easier.

**Comment by rafaqz** [comment]
Transducers.jl is cool. Thanks for benchmarking this. 

One issue is we need to use `broadcast` to make sure this works lazily for disk-based data, as that's how DiskArrays.jl works underneath. There are a few minor problems with the `replace_missing` implementation not always being lazy, but I'll fix them. Now I've checked SentinenlMissings.jl and Transducers.jl solutions don't work over disk-based data, because they call `getindex` directly.

We can actually just use `replace_missing` by default, as its lazy for disk-based data. `Raster` and `RasterStack` could have a `replace_missing=missing` keyword argument that can be set to `nothing` if people don't want this to happen. Or something.

**Comment by maxfreu** [comment]
Hmm is the getindex really a problem for reduction operations? I mean you can just use a view to constrain the area of interest and then plug it into the `Filter`; at some point the data has to be read from disk.

**Comment by rafaqz** [comment]
`getindex` is _the_ problem for disk-based arrays. That's why DiskArrays.jl exists. 

To work around how slow loading indidual points is, we have to fetch data in chunks. And we cant just load everything, because the idea is the large-than-RAM files should still work, and smaller-than-ram files should still read the smallest possible area at the end of all other operations.

**Comment by maxfreu** [comment]
I think I understand the general problem of lazy vs eager data loading. What I tried to say is that if you're just interested in reduction functions, such where there's a single number at the end, like finding the maximum of a subset of your data, then it's probably ok to use transducers as they are now. Broadcasting internals on the other hand are a mystery to me :D

**Comment by rafaqz** [comment]
This isn't a reducing function, its a map over values... But actually anything that calls `getindex` on single values inside some kind of loop over the whole array will fail on disk-based data. And that's what transducers does, as cool as it is otherwise (until someone writes and extension for e.g. DiskArrays.jl that chunks it, at least....). 

Essentially, we cant read single pixels from disk millions of times in any way that is efficient. So we have to call `getindex` on ranges of values that form a _chunk_, instead of single pixels. Maybe the chunk is just a column, or maybe a tile if the file is organised in tiles. Or for a small file, its just the whole thing.

Broadcast is pretty flexible for this. Under the hood we can delay execution load chunks of data instead of single pixels. Solving the too-many disk-reads problem but using familiar syntax that also works equally well on GPU or regular arrays. It works because there are no explicit `getindex` calls until the last possible method in dispatch. And you can just add a `BroadcastStyle` that works differently, getting the data however you want to.

**Comment by maxfreu** [comment]
Ok, I think now I got it. Thanks for your patience. First I thought that wouldn't be too much of a problem, because the gdal cache would catch it once the file is open - but seems like it doesn't help. To proove you right:

```julia
r = Raster(path(st[1][1]))  # some random tif with 15000x150x1 chunks/tiles

open(Raster(path(st[1][1]))) do r
    subset = @view r[1:1500, 1:150, :]
    @time subset |> Filter(x -> x != r.missingval) |> minimum  # 7s
    @time subset |> Filter(x -> x != r.missingval) |> minimum  # 7s
    @time subset = read(subset)  # 0.02s
    @time subset |> Filter(x -> x != r.missingval) |> minimum  # 0.002s
end
```

**Comment by rafaqz** [comment]
The GDAL cache wont always help because the order of chunk indices may not be the same as the iteration order.

But also, the file isn't actually open except when you call `getindex`!! its just a `Rasters.FileArray` holding a `String` path to the filename wrapped deep in whatever broadcasts and functions have been applied to it. Then `Flatten.flatten/reconstruct` replaces the `FileArray` with the real DiskArray when we need to actually get data.

So there are never hanging open files except inside an `open` do block, if you need that. I think this is not a common technique, but is very important for working with large `RasterSeries` and not hitting the operating systems maximum open files limit.

**Comment by maxfreu** [comment]
> There will be a way to break up the Transducers calls into multiple tiled operations, but we dont have it yet.

The result is probably not what you meant, but I took a stab at the problem by defining how to make `Raster`s reducible ([see here](https://juliafolds.github.io/Transducers.jl/stable/howto/reducibles/)). The performance is still sub-par, but calculating the minimum of a view of a disk array is now 35x faster with cache and 100x faster without cache (as far as I understand when caching happens and when not) :)

```julia
using BenchmarkTools
using Rasters
using Transducers
using Transducers: complete, @next
using DiskArrays

const f = "/data_ssd/force/l2/X0031_Y0024/20170202_LEVEL2_SEN2A_BOA.tif";
const r = Raster(f);

# timing with open file to have a cache,
# otherwise the second @time never finishes
open(r) do r
    subset = @view r[1:1500, 1:150, :]
    @btime minimum(skipmissing(Rasters.replace_missing($subset)))
    @btime $subset |> Filter(x -> x != $r.missingval) |> minimum
    subset = read(subset)
    @btime $subset |> Filter(x -> x != $r.missingval) |> minimum
end
# 4.837 ms (1045 allocations: 10.77 MiB)
# 5.742 s (114474023 allocations: 4.72 GiB) <-------- super slow
# 1.829 ms (0 allocations: 0 bytes)


# without open(), for MUCH smaller view
begin
    subset = @view r[1:10, 1:10, 1]
    @btime minimum(skipmissing(Rasters.replace_missing($subset)))
    @btime $subset |> Filter(x -> x != $r.missingval) |> minimum
    subset = read(subset)
    @btime $subset |> Filter(x -> x != $r.missingval) |> minimum
end
# 25.816 ms (327 allocations: 14.58 KiB)
# 2.606 s (17588 allocations: 690.47 KiB) <-------- super slow
# 96.227 ns (0 allocations: 0 bytes)


# now we tell Transducers how to reduce our data:
# https://juliafolds.github.io/Transducers.jl/stable/howto/reducibles/
# this is just a first stab, still loads of allocations
function Transducers.__foldl__(rf, val, r::Raster{<:Any,<:Any,<:Any,<:Any,<:AbstractDiskArray,<:Any,<:Any,<:Any})
    chunksize = size(first(DiskArrays.eachchunk(r)))
    data = similar(r, chunksize...)
    for indices in DiskArrays.eachchunk(r)
        data .= parent(r)[indices]
        for x in data
            val = @next(rf, val, x)
        end
    end
    return complete(rf, val)
end

# now rerun the thing to see the speedup:
open(r) do r
    subset = @view r[1:1500, 1:150, :]
    @btime minimum(skipmissing(Rasters.replace_missing($subset)))
    @btime $subset |> Filter(x -> x != $r.missingval) |> minimum
    subset = read(subset)
    @btime $subset |> Filter(x -> x != $r.missingval) |> minimum
end
# 4.849 ms (1045 allocations: 10.77 MiB)
# 165.090 ms (6466608 allocations: 137.74 MiB)  <-------- 35x faster
# 1.829 ms (0 allocations: 0 bytes)


# without open(), for MUCH smaller view
begin
    subset = @view r[1:10, 1:10, 1]
    @btime minimum(skipmissing(Rasters.replace_missing($subset)))
    @btime $subset |> Filter(x -> x != $r.missingval) |> minimum
    subset = read(subset)
    @btime $subset |> Filter(x -> x != $r.missingval) |> minimum
end
# 25.806 ms (327 allocations: 14.58 KiB)
# 25.795 ms (496 allocations: 16.33 KiB) <-------- 100x faster
# 95.964 ns (0 allocations: 0 bytes)

# without open(), but same view as with open()
begin
    subset = @view r[1:1500, 1:150, :]
    @btime minimum(skipmissing(Rasters.replace_missing($subset)))
    @btime $subset |> Filter(x -> x != $r.missingval) |> minimum
    subset = read(subset)
    @btime $subset |> Filter(x -> x != $r.missingval) |> minimum
end
# 282.857 ms (2280 allocations: 10.81 MiB)
# 428.288 ms (6468055 allocations: 137.79 MiB) <-------- this took AGES before
# 1.829 ms (0 allocations: 0 bytes)```

**Comment by rafaqz** [comment]
@maxfreu this is very cool. We should probably make a TransducersDiskArrays.jl wrapper package that does that generically for any `AbstractDiskArray`, the we can extend it here for `AbstractRaster`.

**Comment by rafaqz** [comment]
One idea I have here, as a start, is to define `skipmissing(A::Raster)` to skip the `missingval` as well as `missing`. It's much faster than base `skipmissing` too, because there is not Union type involved (no matter how much theyre optimised its still slower). 

Even if we switch to automate replacing `missingval` on `getindex` it is still better to do `skpmissing` separately - 5x faster than converting to `missing` and back. 

Seems like wherever we can skip the conversion to missing it will end up being a major performance advantage to not use `missing` directly.

**Comment by vlandau** [comment]
I think that makes a lot of sense. I wonder if for summary functions there could then be a kwarg that defaults to true, e.g.:

```julia
function sum(A::AbstractRaster; skip_missing=True)
    if skip_missing
        return sum(skipmissing(A))
    else
        return sum(A)
    end
end
```

Not sure when anyone wouldn't want to skip the missing values, but in case you want to preserve the option, the above could work.

**Comment by rafaqz** [comment]
Yeah it would be nice. But the problem is defining it for all the methods that might apply, and that we can't set `skippmissing` to `true` by default or we break assumptions from Base julia, especially when you use `sum(A; dims=2)` -- `skippmising` loses any Array shape so you get a totally different return object - a shapeless iterator.

And if we have to use `sum(A; skippmissing=true)`, its more characters than just doing `sum(skipmissing(A))`.

At some point consistency with Base is more important than getting the absolute simplest syntax.

**Comment by vlandau** [comment]
I see -- in that case it is probably best to just define a new method for skipmissing and leave it at that. It's really not much of a burden on the user. I think a prominent placement in the docs about how skipmissing needs to be used in order to get sensible results should suffice.
