### ISSUE TITLE
:filepath for Raster metadata in RasterSeries always set to first raster

### ISSUE THREAD

**Issue by maxfreu** [rafaqz/Rasters.jl#232]
When loading a `RasterSeries` the file paths all loaded `Raster`s are set to the path of the first file. I would expect them to be set to `parent(raster).filename`. I didn't have the time to upload my data, so please resort to you local files for the moment :)

```julia
series = RasterSeries(files, Ti(times))
series[1].metadata[:filepath] == series[2].metadata[:filepath]  # true
```

**Comment by rafaqz** [comment]
Yeah. Set `duplicate_first=false`

https://github.com/rafaqz/Rasters.jl/blob/master/src/series.jl#L66-L69

Probably that should be the default instead of `true`, I actually meant to warn you about that. 

It can be very useful when you don't care about metadata and the dimensions are identical. Otherwise we have to actually load all of the files up front.

**Comment by maxfreu** [comment]
Ouch :D Sorry, didn't read the manual carefully enough, classic... I just needed it for debugging, so usually `true` should be fine.

**Comment by rafaqz** [comment]
I do think this may come up more often tho... Im not sure about the impression of speed vs accuracy and least surprise. Probably people who need speed can set it to true?
