### ISSUE TITLE
Indexing with mappedcrs doesn't work as expected

### ISSUE THREAD

**Issue by maxfreu** [rafaqz/Rasters.jl#247]
Hi! Indexing into an array using coordinates in some mapped crs (here UTM32N) does not work as expected. Am I using it correctly?

```julia
crs_ = WellKnownText{GeoFormatTypes.CRS, String}(GeoFormatTypes.CRS(), "PROJCS[\"BU MEaSUREs Lambert Azimuthal Equal Area - EU - V01\",GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\",6378137,298.257223563,AUTHORITY[\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],PRIMEM[\"Greenwich\",0],UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4326\"]],PROJECTION[\"Lambert_Azimuthal_Equal_Area\"],PARAMETER[\"latitude_of_center\",55],PARAMETER[\"longitude_of_center\",20],PARAMETER[\"false_easting\",0],PARAMETER[\"false_northing\",0],UNIT[\"metre\",1],AXIS[\"Easting\",EAST],AXIS[\"Northing\",NORTH]]")
dims_ = X(Projected(1:100, crs=crs_, order=DimensionalData.ForwardOrdered()))
r = Raster(1:100, (dims_,))
x32n, y32n = AG.reproject((1,0), crs(r), EPSG(25832); order=:trad)
r_mapped = setmappedcrs(r, EPSG(25832))
r[X(At(1))]  # 1
r_mapped[X(Near(x32n))]  # 100, but I expected 1
r_mapped[X(At(x32n))]  # ArgumentError: Can't reproject from ...

typeof(crs_) <: GeoFormat  # true
typeof(EPSG(25832)) <: GeoFormat  # true
```

**Comment by rafaqz** [comment]
Yeah... you cant do this between an azimuthal projection and a cylindrical projection currently. The problem is in the azimuthal projection the X/Y of the conical mappedcrs are not actually independent, like they are in cylindrical projections.

I added the bones of what is required for `selectindices` to work with dependent dimensions early on in DimensionalData.jl, but I never really implemented it in Rasters.jl because: 
1. I basically only use cylindrical projections. And all regular cylindrical projections work fine with `mappedcrs`.
2. I don't know that much about projections!

If you want to write up what is required for this to work that would be amazing.

There are some things for working with CoordinateTransformations like rotations - and this is a similar problem:
https://github.com/rafaqz/DimensionalData.jl/blob/master/src/LookupArrays/lookup_arrays.jl#L408-L430
https://github.com/rafaqz/DimensionalData.jl/blob/master/test/selector.jl#L1058-L1093

**Comment by rafaqz** [comment]
We could do a test in `setmappedcrs` to make sure it can work, and if not make the LookupArrars some kind of `<: Unalligned` type so we can dispatch and process X andY together.

It would mean your example couldn't actually work anyway - you will always need 2 dimensions for this to work.

**Comment by maxfreu** [comment]
Honestly, I didn't think about the projections being azimutal / cylindrical at all. My actual use case was 2D, but that it wont work with 1D makes sense. I also don't know much about projections, so I'm probably the wrong person to implement this. But I'll keep this at the back of my mind and if I really need it might come back to it. Thanks for providing the hints and clarifications.
