### ISSUE TITLE
Support for GRIB files

### ISSUE THREAD

**Issue by tcarion** [rafaqz/Rasters.jl#282]
Hi!

First, thank you a lot for this great package that is helping me a lot with reading netcdf files!
I wanted to know if there was a plan to add support for interfacing GRIB encoded files? 
I saw some discussion about it [here](https://discourse.julialang.org/t/new-package-to-map-grib-files-to-the-unidatas-common-data-model-v4-following-the-cf-conventions/32375) and [here](https://github.com/weech/GRIB.jl/issues/1), but it was some time ago. I also know about [CfGRIB.jl](https://github.com/ecmwf/cfgrib.jl), which can interface GRIB files with `DimensionalData.jl`, but it seems quite unmaintained and it doesn't always work (at least for the files I'm playing with).
So reading GRIB with `Rasters.jl` would actually be great. Is there any WIP on that matter? I'm not a specialist neither in Julia nor in GRIB and I don't really know where to start with, but I would be happy to help :relaxed:

**Comment by rafaqz** [comment]
I didnt even know there was a grib/DimrndionslData package! That should be possible to include into Rasters.jl. 

Raster sources are a little complicated, but you could look at the netcdf as a reference.

I think grib files should be a `RasterStack`. In CfGRIB it's a wrapped NamedTuple of DimArray, which is nearly the same thing.

**Comment by tcarion** [comment]
Yes, I looked at sources of Rasters and it was quite intimidating to me :sweat_smile:. But I'll look at it when I have a bit of time!
Since the CfGRIB package seems quite left behind (and it's not on the official registry), what would be your approach to incorporate it into Rasters.jl ?

**Comment by rafaqz** [comment]
Yes Rasters.jl sources are pretty abstract. They share a lot of code so they all work the same way and have the same syntax, but theyre a bit confusing to write the first time. I'll try to make it easier one day I guess!

As for incorporating CfGRIB.jl, we can either include it directly in Rasters.jl or make a new package. CfGRIB.jl seems dead. Ultimately a grib package that was an analogue of NCDatasets.jl/ArchGDAL.jl might be best, so we're not coupling it to Rasters.jl. 

You would develop it alongside adding a new source to Rasters.jl. The first task is making `OnDiskArray` integrate with DiskArrays.jl.

**Comment by tcarion** [comment]
Hi @rafaqz! I've implemented an essential integration of CfGRIB.jl into Rasters.jl. It won't work for all cases, and there are some improvements to make, but can I ask you if you think I am going in the right direction here? I basically adapted the netcdf sources to the `DataSet` type of CfGRIB.jl.
You can find the code on the [grib branch](https://github.com/tcarion/Rasters.jl/tree/grib) of my Rasters.jl fork. You will need Pkg to install [this branch](https://github.com/tcarion/CfGRIB.jl/tree/for_rasters) of CfGRIB. 
I can also PR to Rasters.jl if it is easier for you. Thank you for your help!

**Comment by rafaqz** [comment]
That looks great! Probably good to make a PR here so we can discuss specific parts of the code more easily.

Some comments: there are still a few `NCDfile` types in there. Also it's not clear if your `Dataset `is opening something in a C library that needs to be closed? that's why most things around opening files happen inside a closure here - e.g. the netcdf `Dataset(f, filename)` function runs a `close` or `destroy` method after running the enclosed code.

**Comment by tcarion** [comment]
Thanks, I did the PR!

As far as I know, the `CfGRIB.DataSet` keeps some information about the indices used to seek the data on the file. Each time `readblock!` is called, the file is open, the data are fetched thanks to these indices, and the file is then closed.

I think it would be nice to implement an interface to GRIB.jl that looks more like NCDatasets, but I don't know how to proceed. I [PRed](https://github.com/ecmwf/cfgrib.jl/pull/25) the `AbstractDiskArray` implementation for now, but I doubt it will be merged anytime soon considering the status of the repo. So should I create a new package (knowing it will probably retake some code from CfGRIB.jl). What about licensing in that case? I'm kind of new to open source contributions, and I don't know how such things usually work :relaxed:

**Comment by rafaqz** [comment]
Its an Apache license so you will need to check MIT/apache compatability and read the Apache terms. You may need to stick with that license and attribute the original authors somehow. But I think its quite open.

For now you can just make basuc something simple that works for this use case. The way you're saying CfGRIB opens files is also how Rasters.jl works (reopening when needed), so youre right there is no need to close `Dataset`.

**Comment by rafaqz** [comment]
See #283

**Comment by rafaqz** [comment]
Ok, Im 100% in support of pure julia backends here. Happy to review PRs for that if you need help.

It iseasier in the long term to have a full julia stack we can understand, profile and debug right to the bottom. For Shapefile.jl and GeoJSON.jl we write 100% julia implementations, so e.g. the raserization methods here are optimised right accross the stack from load up becauae its all julia

Raster data can be more complicated in some cases, and usually we end up falling back to GDAL, netcdf, eccodes etc.

But native is better if you can do it.

**Comment by tcarion** [comment]
I also think it would be great to read GRIB files purely in Julia!
Once ready, I would be happy to depend on this new package in [GRIBDatasets.jl](https://github.com/JuliaGeo/GRIBDatasets.jl) instead of GRIB.jl. 


> See #283
> 
> @tcarion where are we at the merging that PR?

We are currently working on [CommonDataModel.jl](https://github.com/JuliaGeo/CommonDataModel.jl), which would simplify the integration of NetCDF and GRIB files in Rasters (and maybe also [TIFF files](https://github.com/Alexander-Barth/TIFFDatasets.jl) ?). See https://github.com/JuliaGeo/GRIBDatasets.jl/issues/7 and https://github.com/JuliaGeo/GRIBDatasets.jl/issues/8.

I see two options here; either we already merge #283 and create another PR when the implementation of CommonDataModel is ready, or we close it and wait for this new implementation. If you prefer the first option, I will rebase with main and I think it will be ready to be merged.

**Comment by eliteuser26** [comment]
Hi. I've been reading on the Gribdatasets and liked what I saw with this project. Reading both Grib and Netcdf in Julia is great. I will support it as a lot of good code was developed for it.

1. I would like to say from the start that I'm new to Julia but I'm picking up the language very quickly. I've have a lot of experience with Python so that is the reason why I see a parallel between Python and Julia.

2. My pure Julia Grib package isn't anywhere ready for distribution just yet. I'm missing some big pieces that I need to understand to decode the data part. If you have suggestions or comments I'm open to ideas. I was able to decode all sections in a Grib message quite easily except for the data. That part is done. I'm redoing the code from the Grib.jl package so I can use it in Windows. I'm also recreating the Ecmwf tables in CSV format. Created a code for this too.

3. I think you should go ahead with your original plan. I'm not sure how long it will take to finalize my package. I will still need to put in documentation and examples according to Julia instructions. Then I should be able to disseminate this package in GitHub.

Hope this answers some of your questions.

**Comment by tcarion** [comment]
I appreciate your enthusiasm about GRIBDatasets :-). 
Yes we will keep using GRIB.jl for now, but don't hesitate to notify me when your code is available. I can even try to help!
