### ISSUE TITLE
Release notes seem to be off

### ISSUE THREAD

**Issue by mauro3** [rafaqz/Rasters.jl#353]
Looking at the release notes https://github.com/rafaqz/Rasters.jl/releases/tag/v0.5.0 I see that many of the carried over from previous releases, see https://github.com/rafaqz/Rasters.jl/releases?page=3; presumably something's off with the autogeneration.

Also, clicking on "Releases" on the main page gets one to https://github.com/rafaqz/Rasters.jl/releases, which first list the old GeoData.jl releases.  Not sure something can be done about this though.

Last, just a wish: I just had a look at https://github.com/rafaqz/Rasters.jl/releases/tag/v0.5.0 and I don't know what is breaking. Would be great if it was documented, just a "(breaking)" behind the closed issue/merged PR would be perfect.

**Comment by rafaqz** [comment]
Wow yes seems that has been happening since v0.4.0. Could this be a Tagbot problem? Or is it a github thing? I honestly have no idea how that actually works and calculates the changes. Maybe we should make sure the tagbot script is correct.

But, if the releases were accurate you could see what is breaking its:

https://github.com/rafaqz/Rasters.jl/pull/352

which changes `getproperties` on `RasterStack` so its like a `NamedTuple` and retrieves its `Raster` layers by name. Before it was just `getfield`. Nothing else breaks.

**Comment by rafaqz** [comment]
Ok fixed:
https://github.com/rafaqz/Rasters.jl/releases

**Comment by rafaqz** [comment]
Maybe we should always put BREAKING in the PR title so its easier to see which one is responsible

**Comment by mauro3** [comment]
Excellent, thanks to much!

**Comment by rafaqz** [comment]
Thanks for pointing it out those were very confusing release notes
