### ISSUE TITLE
How do I add a `Raster` to a `RasterStack`?

### ISSUE THREAD

**Issue by tomchor** [rafaqz/Rasters.jl#420]
Sorry to have to ask a naive question like this, but how do I add a `Raster` to a `RasterStack`?

In particular I'm trying to add back one of the RasterStack fields after an operation. In my head, it would go something like this:

```julia
using Rasters
url = "https://www.unidata.ucar.edu/software/netcdf/examples/tos_O1_2001-2002.nc";
filename = download(url, "tos_O1_2001-2002.nc");
A = RasterStack(filename)

B = log10.(A.tos)
set!(B, name => :log10tos)
push!(A, B)
```

But of course the last two lines don't work. How can I do this?

Thanks!

**Comment by rafaqz** [comment]
Yeah, we need better docs for this for sure.

But think of a RasterStack more like a `NamedTuple` than a `Dict`. It often actually is a `NamedTuple` inside.

So mutating functions with a `!` can only be operating on the contents of the arrays, never the structure of the stack - because it's immutable.

But instead to we can merge like a `NamedTuple`, you will get a new `RasterStack` back if you merge a `NamedTuple` of `Raster` into it:
```julia
newstack = merge(A, (log_tos=log10.(A.tos),))
```

You could also do this:
```julia
newstack = RasterStack((; A..., log_tos=log10.(A.tos)))
```

To subset a stack you can index like with a NamedTuple:

```julia
newstack[(:tos, :log_tos)]
```

**Comment by tomchor** [comment]
Thanks! Would you like me to open a PR and include an example like this in the docs?

**Comment by rafaqz** [comment]
I would _akways_ like a docs PR.

But note there is a major docs rewrite in the @lazarusA PR, you may be best dping a PR against that.

You can also add it to DimensionalData.jl, as thats where the behaviour is from and stacks are really under documented there too.
