### ISSUE TITLE
add direct (test?) dependency on GDAL

### ISSUE THREAD

**Issue by visr** [rafaqz/Rasters.jl#521]
See https://github.com/JuliaGeo/GDAL.jl/pull/161#issuecomment-1731797608

**Comment by rafaqz** [comment]
Turns out this isnt so easy. GDAL is not available because we load ArchGDAL in an extension.

I guess we need to add a separare GDAL extension for the methods that use it, which will just load automatically when people load ArchGDAL? 

It could be better to move those few methods to ArchGDAL instead?

**Comment by visr** [comment]
Hmm yeah I don't know about those methods, but moving them to ArchGDAL sounds like a better option.

**Comment by rafaqz** [comment]
Its things like `GDAL.gdalgetrasternodatavalue` which could totally be in ArchGDAL.

**Comment by rafaqz** [comment]
I removed the Aqua test here so the GDAL tests will at least work.
