### ISSUE TITLE
Optimise extract for `Regular` lookups

### ISSUE THREAD

**Issue by alex-s-gardner** [rafaqz/Rasters.jl#625]
I feel like this is an incredibly naïve question but I don't think I've been able to find the proper way to index into a Raster with a list of points.

Here's what I do now:
```julia
using Rasters
# Rasters v0.10.1

x = X(0.5:0.1:90);
y = Y(0.5:0.1:90);
A = Raster(zeros(UInt8, y, x))

f = GeoInterface.PointTuple.([(X=1.4, Y=9.9), (X=1.3, Y=10), (X=70, Y=30)])

pts = extract(A, f, atol=0.2; index=true, geometry=false)
```

For very large datasets this is slower than I would expect and requires me to specify a tolerance which is a bit of a hassle, so I try to see if I can use Near() on points handed to `extract` like this:

```
pts = extract(A, Near(f); index=true, geometry=false)
```

But that doesn't work. Next I tried

```
v = similar(A, 0)
for (x, y) in f
    push!(v, A[X(Near(x)), Y(Near(y))])
end
```

But this was much slower than extract.

Is there a better way to do what I'm trying to do?

Thanks!

**Comment by rafaqz** [comment]
Your raster data is Points not Intervals? Thats why `atol` is needed.

**Comment by alex-s-gardner** [comment]
What if `atol` was automatically set to the smallest grid resolution?

**Comment by alex-s-gardner** [comment]
I'm not sure if this will work for Rasters.jl generally but I've found it faster (2x), for large numbers of points, to calculate the index directly and avoid using `extract`:

```julia
pt_x = getindex.(f,1)
pt_y = getindex.(f,2)

r = round.(Int64,(pt_x .- x[1])./step(x)).+1
c = round.(Int64, (pt_y .- y[1]) ./ step(y)).+1

idx = [CartesianIndex(a,b) for (a,b) in  zip(r,c)]

A[idx]
```

**Comment by rafaqz** [comment]
We should implement something like that yes. But it only works when your lookup is a fixed step range (some netcdf dimensions are not), and what we have now is generic.

And we can't index to half steps for Points because its missing the whole "point" of having them! They don't span the whole interval. There is just no data between them. If there is data to extract between your points, what you have should be intervals. 

I know GDAL only half heartedly implements points and intervals, but we do it properly here ;)

**Comment by rafaqz** [comment]
@alex-s-gardner wondering if you agree that switching sampling to `Intervals()` is a tolerable solution here.

**Comment by alex-s-gardner** [comment]
`Intervals()` vs `Points()` is undocumented. How would it change the behavior of `extract`?

**Comment by rafaqz** [comment]
It may not be amazingly well documented but it is documented:
https://rafaqz.github.io/DimensionalData.jl/v0.26.7/api/lookuparrays#DimensionalData.Dimensions.Lookups.Intervals
https://rafaqz.github.io/DimensionalData.jl/v0.26.7/selectors#Lookups

And most of the junk printed in the repl along with a Raster is actually useful information!! It shows if you have points or intervals for each dimension. Points are the default, because they are the simplest.

Most of these things are in DimensionalData.jl. 

```julia
using Rasters.LookupArrays
Rasters.set(raster, X=Intervals(), Y=Intervals())
```

But you probably know if the lookup values represent the start or center of the pixel. If they are the start like in GDAL you want to specify that, as center is the default :

```julia
Rasters.(raster, X=Intervals(Start()), Y=Intervals(Start()))
```

**Comment by rafaqz** [comment]
In this example the quick way is to pass the `sampling` keyword to the dimension constructor - which will forward it to the detected lookup:

```julia
x = X(0.5:0.1:90; sampling=Intervals(Start()));
y = Y(0.5:0.1:90; sampling=Intervals(Start()));
A = Raster(zeros(UInt8, y, x))
```

**Comment by alex-s-gardner** [comment]
Does `extract` behave differently for `Intervals()`?   Just changing the Rater to intervals had no impact on performance.

**Comment by rafaqz** [comment]
Im fixing your complaint about needing atol??

**Comment by rafaqz** [comment]
I will PR at some stage with your performance suggestion too.

The issue is we need to separate out dispatch just for `Regular` lookups where that optimisation is possible.

**Comment by rafaqz** [comment]
@tiemvanderdeure also thinks the option of using `Near` would also be good for `Points` to avoid `atol`. So we can have that too - at least it makes it explicit what we are doing.
